# Generated by Django 5.2.16 on 2026-10-07 06:14

import django.utils.timezone
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'created'), ('edited', 'edited'), ('ticked', 'ticked'), ('reversed', 'reversed')], max_length=20)),
                ('stage', models.CharField(blank=True, choices=[('received', 'Order received'), ('ordered', 'Material ordered'), ('arrived', 'Material received'), ('dispatch', 'Dispatch'), ('delivered', 'Delivered')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('actor_name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_entries',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('stage', models.CharField(choices=[('received', 'Order received'), ('ordered', 'Material ordered'), ('arrived', 'Material received'), ('dispatch', 'Dispatch'), ('delivered', 'Delivered')], max_length=20)),
            ],
            options={
                'db_table': 'duties',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=10)),
                ('site', models.CharField(blank=True, max_length=120)),
                ('contractor', models.CharField(blank=True, max_length=80)),
                ('mode', models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='Pickup', max_length=10)),
                ('due', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('track_token', models.CharField(default=jobs.models.new_track_token, max_length=32, unique=True)),
                ('stage_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='JobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('laminate', 'Laminate'), ('adhesive', 'Adhesive'), ('ply', 'Plywood'), ('louver', 'Louvers'), ('veneer', 'Veneers'), ('door', 'Doors')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=60)),
                ('thickness', models.CharField(blank=True, max_length=60)),
                ('size', models.CharField(blank=True, max_length=60)),
                ('pack', models.CharField(blank=True, max_length=60)),
                ('qty', models.PositiveIntegerField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'job_items',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessageWording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('lang', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], max_length=2)),
                ('body', models.CharField(max_length=700)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'message_wordings',
            },
        ),
        migrations.CreateModel(
            name='RosterDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'roster_days',
            },
        ),
        migrations.CreateModel(
            name='StageTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('received', 'Order received'), ('ordered', 'Material ordered'), ('arrived', 'Material received'), ('dispatch', 'Dispatch'), ('delivered', 'Delivered')], max_length=20)),
                ('done_by_name', models.CharField(max_length=80)),
                ('done_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'stage_ticks',
            },
        ),
        migrations.CreateModel(
            name='WorkSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'work_sent',
            },
        ),
    ]
