# Generated by Django 5.2.16 on 2026-10-07 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditentry',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='messagewording',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagetick',
            name='done_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagetick',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='worksent',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worksent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='duty',
            constraint=models.UniqueConstraint(fields=('day', 'user', 'stage'), name='one_duty_per_worker_step_day'),
        ),
        migrations.AddConstraint(
            model_name='messagewording',
            constraint=models.UniqueConstraint(fields=('key', 'lang'), name='one_wording_per_message_language'),
        ),
        migrations.AddConstraint(
            model_name='stagetick',
            constraint=models.UniqueConstraint(fields=('job', 'stage'), name='one_tick_per_stage'),
        ),
        migrations.AddConstraint(
            model_name='worksent',
            constraint=models.UniqueConstraint(fields=('day', 'user'), name='one_work_message_per_worker_day'),
        ),
    ]
