# Generated by Django 5.2.16 on 2026-10-07 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_message_id', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('replied', models.CharField(blank=True, max_length=20)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'incoming_messages',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='action',
            field=models.CharField(choices=[('created', 'created'), ('edited', 'edited'), ('ticked', 'ticked'), ('reversed', 'reversed'), ('messaged', 'messaged'), ('message_failed', 'message_failed')], max_length=20),
        ),
        migrations.CreateModel(
            name='IncomingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_url', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incoming_links',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('lang', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], max_length=2)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('element_name', models.CharField(max_length=120)),
                ('content', models.CharField(max_length=1024)),
                ('params', models.CharField(max_length=80)),
                ('provider_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', "Waiting for WhatsApp's approval"), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Not submitted')], default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'whatsapp_templates',
                'ordering': ['key', 'lang', 'version'],
                'constraints': [models.UniqueConstraint(fields=('key', 'lang', 'version'), name='one_template_per_message_language_version')],
            },
        ),
    ]
