# Generated by Django 5.2.16 on 2026-10-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitem',
            name='category',
            field=models.CharField(choices=[('laminate', 'Laminate'), ('adhesive', 'Adhesive'), ('ply', 'Plywood'), ('louver', 'Louvers'), ('veneer', 'Veneers'), ('door', 'Doors'), ('other', 'Other')], max_length=20),
        ),
    ]
